-- ============================================
-- Meu Checkout - Entrega segura de e-books
-- Execute este SQL no Supabase Dashboard > SQL Editor
-- ============================================

-- 1. Adiciona coluna arquivo_path na tabela produtos
ALTER TABLE produtos
ADD COLUMN IF NOT EXISTS arquivo_path text;

COMMENT ON COLUMN produtos.arquivo_path IS 'Caminho do arquivo no bucket privado "ebooks" (ex: financas-pessoais.pdf). Usado para gerar Signed URL após pagamento confirmado.';

-- 2. Tabela de downloads (para métricas futuras do dashboard)
CREATE TABLE IF NOT EXISTS downloads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  produto_id bigint NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
  external_reference text,
  arquivo_path text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Índices úteis para o futuro dashboard
CREATE INDEX IF NOT EXISTS idx_downloads_pedido_id ON downloads(pedido_id);
CREATE INDEX IF NOT EXISTS idx_downloads_produto_id ON downloads(produto_id);
CREATE INDEX IF NOT EXISTS idx_downloads_created_at ON downloads(created_at);

COMMENT ON TABLE downloads IS 'Registro de cada solicitação de download válida. Usado para métricas de vendas e engajamento no dashboard administrativo.';

-- 3. RLS na tabela downloads
ALTER TABLE downloads ENABLE ROW LEVEL SECURITY;

-- Nenhuma política pública. Apenas service role (Edge Functions) e futuramente o dashboard admin poderão inserir/ler.
-- (Não criamos políticas de SELECT/INSERT para anon ou authenticated)

-- ============================================
-- Fim do SQL
-- Após executar:
-- 1. Crie o bucket "ebooks" (privado) em Storage
-- 2. Faça upload de um PDF de teste (ex: teste.pdf)
-- 3. Atualize o produto id=1 com:
--    UPDATE produtos SET arquivo_path = 'teste.pdf' WHERE id = 1;
-- ============================================
