-- ============================================
-- Recuperacao de acesso aos cursos (link por e-mail)
-- Execute no Supabase Dashboard > SQL Editor
-- Nao altera pedidos, pagamentos nem produtos.
-- ============================================

CREATE TABLE IF NOT EXISTS public.acesso_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  token text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_acesso_tokens_email ON public.acesso_tokens (email);
CREATE INDEX IF NOT EXISTS idx_acesso_tokens_token ON public.acesso_tokens (token);
CREATE INDEX IF NOT EXISTS idx_acesso_tokens_expires ON public.acesso_tokens (expires_at);

COMMENT ON TABLE public.acesso_tokens IS 'Tokens temporarios enviados por e-mail para recuperar acesso aos cursos comprados.';

ALTER TABLE public.acesso_tokens ENABLE ROW LEVEL SECURITY;
-- Sem politicas publicas: apenas service role (Edge Functions).

-- ============================================
-- Fim. Proximo passo: implantar Edge Functions
-- solicitar-acesso e validar-acesso
-- ============================================
